### ISSUE TITLE
Dependency broken to fido2.ctap2 module

### ISSUE THREAD

**Issue by Corpswalker** [dany74q/ctap-keyring-device#6]
Hi,
fido2 was released in version 1.0.0 and it removed **AttestedCredentialData** from _fido2.ctap2_ module. 

The reference in ctap_keyring_device/ctap_keyring_device.py on line 19 is not available anymore.

Here is the output which led me here:
```
corpswalker@archdev:/usr/bin$ gimme-aws-creds 
Traceback (most recent call last): 
 File "/usr/bin/gimme-aws-creds", line 13, in <module> 
   from gimme_aws_creds.main import GimmeAWSCreds 
 File "/usr/lib/python3.10/site-packages/gimme_aws_creds/main.py", line 32, in <module> 
   from .okta import OktaClient 
 File "/usr/lib/python3.10/site-packages/gimme_aws_creds/okta.py", line 34, in <module> 
   from gimme_aws_creds.webauthn import WebAuthnClient, FakeAssertion 
 File "/usr/lib/python3.10/site-packages/gimme_aws_creds/webauthn.py", line 18, in <module> 
   from ctap_keyring_device.ctap_keyring_device import CtapKeyringDevice 
 File "/usr/lib/python3.10/site-packages/ctap_keyring_device/ctap_keyring_device.py", line 18, in <module> 
   from fido2.ctap2 import ( 
ImportError: cannot import name 'AttestedCredentialData' from 'fido2.ctap2' (/usr/lib/python3.10/site-packages/fido2/ctap2/__init__.py)
```

**Comment by dany74q** [comment]
Thanks !

Dealt w/ it here - https://github.com/dany74q/ctap-keyring-device/pull/9
I'll need to pin the previous version in gimme-aws-creds (the biggest user of this library) before creating a new tag with the changes, as the bump to fido2 v1.0.0 contains some breaking changes.

**Comment by zelch** [comment]
Hello @dany74q !

Any update on releasing 2.0.0?
